services:
  - type: web
    name: brainbytes-backend
    env: node
    rootDir: brainbytes-multi-container/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: MONGO_URI=mongodb://Cate1202:4CF.bz5rxPERc8D@cluster0-shard-00-00.sfsf6.mongodb.net:27017,cluster0-shard-00-01.sfsf6.mongodb.net:27017,cluster0-shard-00-02.sfsf6.mongodb.net:27017/?ssl=true&replicaSet=atlas-XXXXXX-shard-0&authSource=admin&retryWrites=true&w=majority
      - key: CLIENT_ORIGIN
        value: https://brainbytes-frontend.onrender.com
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: brainbytes-frontend
    env: static
    rootDir: brainbytes-multi-container/frontend
    buildCommand: npm install && npm run build && npm run export
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://brainbytes-backend.onrender.com
