{
 "title": "BrainBytes - System Overview Dashboard",
 "description": "User experience metrics for the BrainBytes platform",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "BrainBytes - System Overview Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Usage",
   "type": "piechart",
   "description": "Shows total CPU usage of the Node.js backend container.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage (GB)",
   "type": "gauge",
   "description": "This shows % used per instance",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Questions per Session (avg)",
   "type": "timeseries",
   "description": "Displays the average number of questions asked per tutoring session, helping assess student engagement over time.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_requests_total{route=\"/question/ask\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Session Traffic Trends",
   "type": "timeseries",
   "description": "Session traffic trends and compare start vs. end rate.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_requests_total{route=\"/session/start\"}[1m])",
     "legendFormat": "{{route}}"
    },
    {
     "expr": "rate(http_requests_total{route=\"/session/end\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}