{
 "title": "BrainBytes - Application Performance",
 "description": "Application-level metrics for BrainBytes platform",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BrainBytes - Application Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "Displays the total number of HTTP requests received by the backend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{job}}{{name}}{{route}}" }
   ]
  },
  {
   "title": "HTTP Request Rate (1m)",
   "type": "timeseries",
   "description": "This gives per-second request rates over the last 1 minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(brainbytes_http_requests_total[1m])",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Total Requests by Route",
   "type": "timeseries",
   "description": "All-time total volume by route.\nrate(http_requests_total[1m]): calculates per-second increase (average over 1 minute).\n\nsum by (route)(...): aggregates the rate by each API route like /question/ask, /session/start, etc.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (route) (rate(brainbytes_http_requests_total[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "description": "Error Rate Panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  }
 ]
}