services:
  - type: web
    name: brain-bytes-app
    env: node
    rootDir: backend
    buildCommand: |
      cd ../frontend
      npm install
      npm run build
      cd ../backend
      npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: your-mongo-uri-here
      - key: CLIENT_ORIGIN
        value: https://brain-bytes-1.onrender.com
      - key: GROQ_API_KEY
        sync: false
