services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:10000"
    environment:
      - PORT=10000
      - MONGO_URI=mongodb://mongodb:27017/brainbytes
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CLIENT_ORIGIN=http://localhost:4001
    depends_on:
      - mongodb
    networks:
      - brainbytes-network

  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - brainbytes-network

volumes:
  mongodb-data:

networks:
  brainbytes-network:
    driver: bridge
