version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - brainbytes-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - brainbytes-network
    restart: unless-stopped


  mongo:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - brainbytes-network

volumes:
  mongodb-data:

networks:
  brainbytes-network:
    driver: bridge
